name: Build, Push, and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up env
      run: echo ${{ secrets.ENV_FILE }} > .env

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t jake0526/pabuaya-portfolio:production .

    - name: Push Docker image
      run: docker push jake0526/pabuaya-portfolio:production

    - name: Install Kustomize (v5.0.1)
      run: |
        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash -s -- 5.0.1
        sudo mv kustomize /usr/local/bin/kustomize

    - name: Configure kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
        chmod 600 ~/.kube/config

    - name: Deploy to Kubernetes
      run: |
        export KUBE_NAMESPACE=rresidencia
        envsubst < k8s.yaml | kubectl --namespace=$KUBE_NAMESPACE apply -f -
        kubectl rollout restart deployment pabuaya-portfolio-production -n $KUBE_NAMESPACE || echo "First pod"
