name: Build, Push, and Deploy

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t jake0526/pabuaya-portfolio:production .

    - name: Push Docker image
      run: docker push jake0526/pabuaya-portfolio:production

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.22.0'  # Specify the kubectl version you need

    - name: Configure kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
        chmod 600 ~/.kube/config

    - name: Deploy to Kubernetes
      run: |
        export KUBE_NAMESPACE=rresidencia
        envsubst < k8s.yaml | kubectl --namespace=$KUBE_NAMESPACE apply -f -
        kubectl rollout restart deployment pabuaya-portfolio-production -n $KUBE_NAMESPACE || echo "First pod"
